services:
  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
